[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
[dev]
command = "npm run dev"  # Or "yarn dev"
targetPort = 8080        # Your Vite/React app port
functions = "netlify/functions"
port = 8888              # Port netlify dev runs on
